version: "3.9"
services:
  store:
    image: prompto/mongo:4.4
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${PROMPTO_DATA}:/mnt/prompto
  factory:
    image: ${FACTORY_IMAGE}
    ports:
      - "${FACTORY_PORT}:80"
      - "${DEVELOPER_PORT}:8000"
    volumes:
      - ${PROMPTO_DATA}:/mnt/prompto
    depends_on:
      - store
