secretKey: &secretKey
  factory: prompto.security.AwsKMSSecretKeyFactory
  alias: prompto/seed
  awsRegion: us-east-1

secret: &secret AQICAHiWGTkxd74dNcn82U2E7Y/aoKsK58VZ26N/OSsr01yfrAGaKPSMtmv7mB9f32G1Epn9AAAAajBoBgkqhkiG9w0BBwagWzBZAgEAMFQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMo2VIeuZWJGxBFgZDAgEQgCdm21syTkfHO+7i+KgrxobSHr7OgoulC47YucABjKpTY9Od6vUGjcU=

mongoStore: &dockerMongoStore
  factory: prompto.store.mongo.MongoStoreFactory
  host: store
  port: 27017

codeStore:
  <<: *dockerMongoStore
  dbName: FACTORY

dataStore:
  <<: *dockerMongoStore
  dbName: APPS

target:
  dataStore:
    <<: *dockerMongoStore
    dbName: DATA
  portRange:
    minPort: 8000
    maxPort: 8000

http:
  publicAddress: docker
  protocol: http
  port: 80
